### ISSUE TITLE
Uncaught Exception

### ISSUE THREAD

**Issue by thismarvin** [austin0209/minetone-movie-bot#13]
In the following excerpt of code, ```requests.get(url)``` could potentially throw a ```requests.exceptions.ConnectionError``` if the bot loses connection with the internet. 

https://github.com/austin0209/minetone-movie-bot/blob/0ea3cf6f425e8854068d12d4017334fd67c3bac8/responses.py#L67-L77

There may also be other exceptions we are not considering. In order to prevent the bot from crashing, simply moving ```requests.get(url)``` inside the try block should avert any unexpected crashes!

**Comment by austin0209** [comment]
Fixed as per e875a9afb214d185ec51885c4382a03948b01675. Thanks for pointing it out!
